### ISSUE TITLE
couch-sidecar folder is missing

### ISSUE THREAD

**Issue by SukantGujar** [6fusion/couch-kubernetes#4]
This folder is referenced by `Dockerfile.sidecar`, but is missing in the repo.

**Comment by p80n** [comment]
`couch-sidecar` is not actually a folder. It's the go binary responsible for setting up the cluster, and is already included in the docker image `6fusion/couch-sidecar`. 
But I've updated the README to include instructions on building it from source, if you prefer. I've left them fairly minimal on purpose, since there are lots of articles on the web about how to build go applications.
Feel free to take a look though (at the bottom of the README) and let me know if you have any other questions.

**Comment by SukantGujar** [comment]
Thanks, missed the file for some reason. Will give it a spin.
